AppiumURL=https://dev-in-blr-0.headspin.io:3012/v0/a039649c32eb406ea479a93941a1de37/wd/hub
Udid=RZ8NA0Z723M
Package=org.zwanoo.android.speedtest
Activity=com.ookla.mobile4.screens.main.MainActivity



######################################